"""Varchar limit changed

Revision ID: 85f5bd801416
Revises: d704893ecab2
Create Date: 2025-03-07 14:19:40.372207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85f5bd801416'
down_revision: Union[str, None] = 'd704893ecab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'description',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.VARCHAR(length=600),
               existing_nullable=True)
    op.alter_column('products', 'description',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.VARCHAR(length=600),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'description',
               existing_type=sa.VARCHAR(length=600),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('categories', 'description',
               existing_type=sa.VARCHAR(length=600),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    # ### end Alembic commands ###
