"""cart table added

Revision ID: c1683a75e896
Revises: edf114a835fb
Create Date: 2025-03-05 20:09:49.082421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1683a75e896'
down_revision: Union[str, None] = 'edf114a835fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carts',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('product_id', sa.BIGINT(), nullable=True),
    sa.Column('user_id', sa.BIGINT(), nullable=True),
    sa.Column('quantity', sa.SMALLINT(), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('carts_product_id_key', 'reviews', ['product_id'], unique=False, schema='public')
    op.create_index('carts_user_id_key', 'reviews', ['user_id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('carts_user_id_key', table_name='reviews', schema='public')
    op.drop_index('carts_product_id_key', table_name='reviews', schema='public')
    op.drop_table('carts', schema='public')
    # ### end Alembic commands ###
