"""Varchar limit changed

Revision ID: d704893ecab2
Revises: c1683a75e896
Create Date: 2025-03-07 13:49:12.966823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd704893ecab2'
down_revision: Union[str, None] = 'c1683a75e896'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.VARCHAR(length=400),
               existing_nullable=False)
    op.alter_column('products', 'description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('products', 'description',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('categories', 'description',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
