"""image_url added in product

Revision ID: edf114a835fb
Revises: 7285488f00f4
Create Date: 2025-02-06 12:30:26.187079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'edf114a835fb'
down_revision: Union[str, None] = '7285488f00f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('products', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('products', 'image_urls')
    # ### end Alembic commands ###
